version: '3'

services:
  app:
    image: naphawan12/strapi:1.0.0
    container_name: 67-ced-strapi
    ports:
      - '8080:1337'
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=67_app_uat
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
    env_file:
      - .env

  db:
    container_name: 67-ced-db
    image: postgres:15-bullseye
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=67_app_uat
    env_file:
      - .env